### ISSUE TITLE
./zwift.sh: line 180: xhost: command not found

### ISSUE THREAD

**Issue by netbrain** [netbrain/zwift#126]
**Describe the bug**
Some distributions don't have xhost, i.e wayland only.

**To Reproduce**
1. System doesn't have xhost
2. Launch zwift
3. See error

Script should probably only invoke xhost if it finds it on the path.  something ala.

`command -v xhost && xhost ....`

**Comment by netbrain** [comment]
Sure, sounds like a good plan.

**Comment by sHedC** [comment]
Did a first update to the zwift.sh, and some fancy stuff.

What you think ? https://github.com/netbrain/zwift/tree/sHedC/issue126

I did try to use Pipewire instead of Pulse in wayland but no idea if it worked as even without the pulse settings I still got sound.

Also just did minor updates to make sure wayland can work, as setting it in the run-zwift.sh is too late so set it in build and then use DISPLAY to indicate if wayland experimental or X.
