### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by markus1189** [netbrain/zwift#59]
This is not really an issue, just a message for you.  Feel free to close this after reading.

I wanted to thank you for this project.  My `wine` setup broke locally after another update and I was stuck without Zwift when I wanted to workout which is really annoying.

Found this project and it just works like a charm, so than you for all the work!

**Comment by netbrain** [comment]
Nice to hear, thank you. Yes my intention with this project was to have a place where we can collaborate on creating a reliable Zwift setup that will hopefully work for all. And when there are issues, more people can help in resolving them.

It's not by any stretch a perfect solution today, but I think it gives the majority of its users a pretty pain free and simple setup. As all software should be!

Cheers.

**Comment by netbrain** [comment]
Oh, and by any chance would you have the know how and willingness to support me on #28? I see you have som nix in you :wink:

**Comment by markus1189** [comment]
I'd sure be willing, just need to understand what the concrete problem is you want to solve ;)

**Comment by netbrain** [comment]
@markus1189 As said in the issue, i'd really like to explore a nix flake that could build the different described variants. However the concept of impure/pure builds as well as the sandboxed environment given for builds makes the building and installation of zwift quite challenging. Especially since nix is not my strong suit. I have tried a couple of experiments, but nothing that's produced anything concrete.
