### ISSUE TITLE
[HELP]issue installing using podman

### ISSUE THREAD

**Issue by HeavyD2k** [netbrain/zwift#61]
hello, 

i was digging around and i see in zwift.sh you recomand to use podman.
is i install zwift with sudo than i can't launch it becouse permmisions issues becouse podman should be run as normal user.
But when i to install as user after he pulls the files from server it eats up all the space on the disk (around 30 GB)
is there a way to use in coretly with podman or just i should try to use docker?

Thank you

**Comment by HeavyD2k** [comment]
this is the output when i am launching with sudo

ergo@gergo-Ubuntu:~$ sudo zwift
[sudo] password for gergo: 
+ IMAGE=docker.io/netbrain/zwift
+ VERSION=latest
+ [[ ! -n '' ]]
++ command -v podman
+ [[ -x /usr/bin/podman ]]
+ CONTAINER_TOOL=podman
+ [[ ! -n '' ]]
+ podman pull docker.io/netbrain/zwift:latest
Trying to pull docker.io/netbrain/zwift:latest...
Getting image source signatures
Copying blob 805973e01112 skipped: already exists  
Copying blob 7ee5662817e5 skipped: already exists  
Copying blob af107e978371 skipped: already exists  
Copying blob 0244cebf8ce0 skipped: already exists  
Copying blob c7a6c877c692 skipped: already exists  
Copying blob c12b90972c9a skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 5581a179d053 skipped: already exists  
Copying blob 048dd7fba9b3 skipped: already exists  
Copying blob acda75c3d8a6 skipped: already exists  
Copying blob 88fdd97476df skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 39845142d014 skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 9d6304cd9ec1 skipped: already exists  
Copying blob d085b5e4892a skipped: already exists  
Copying blob 5c4fc310ba37 skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob acf75673be3d skipped: already exists  
Copying blob 80d072da34cf skipped: already exists  
Copying config f066baeabe done  
Writing manifest to image destination
Storing signatures
f066baeabe6842d81d677764dec1d5bdabc23aac106ac7f6dd7534580d04cf7f
+ [[ -f /proc/driver/nvidia/version ]]
+ VGA_DEVICE_FLAG='--device /dev/dri:/dev/dri'
+++ '[' podman = podman ']'
+++ echo --userns=keep-id
++ podman run -d --rm --privileged -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/0/pulse:/run/user/1000/pulse -v zwift-root:/home/user/Zwift --userns=keep-id --device /dev/dri:/dev/dri docker.io/netbrain/zwift:latest
Error: keep-id is only supported in rootless mode
+ CONTAINER=
+ [[ -z '' ]]
++ podman inspect '--format={{ .Config.Hostname  }}'
Error: no names or ids specified
+ xhost +local:
non-network local connections being added to access control list
gergo@gergo-Ubuntu:~$

**Comment by netbrain** [comment]
First of all you shouldn't run as sudo. All you need to do is run ./zwift.sh that's it.

If you have podman installed, it will prefer that over docker. But you can pick and choose using the environment variables provided in the README.

i.e if you want to run using docker do `CONTAINER_TOOL=docker zwift.sh` and `CONTAINER_TOOL=podman zwift.sh` for podman. But as i said, this is only if you wan't to override the defaults.

zwift.sh is simply a wrapper script to run the real container command. In your case the real command actually invoked is. `podman run -d --rm --privileged -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/0/pulse:/run/user/1000/pulse -v zwift-root:/home/user/Zwift --userns=keep-id --device /dev/dri:/dev/dri docker.io/netbrain/zwift:latest`

The reason you are getting the error is because you are running podman as root.  As for docker vs podman, it's up to you. Some prefer podman, others don't mind docker. The benefit of podman is that it's a userland application and doesn't require root access on the system. Docker however does.

**Comment by HeavyD2k** [comment]
Hey, thx for clarification.
Have you faced in podman when you pulling(not rooted) the containers it wil eat up all the space on your drive?
I have around 30 gb free but after the pool is done the space on the drive disappears and script gives error that drive out of space :(

**Comment by netbrain** [comment]
You can cleanup your system using a combination of
`
$CONTAINER_TOOL system prune
$CONTAINER_TOOL images
$CONTAINER_TOOL rmi <image-id>
`

**Comment by HeavyD2k** [comment]
Yes i did that, but when trying to pul zwift it eats all up. When pulling with sudo it goes flawless but with than it's giving me other errors because of sudo.

**Comment by netbrain** [comment]
you probably have corrupted your file permissions when you used sudo. You will have to look into the podman documentation for where they actually store the container data, and forcibly remove them.
